kind: Service
apiVersion: v1
metadata:
  name: sas-event-stream-processing-studio-app
spec:
  selector:
    app: sas-event-stream-processing-studio-app
  ports:
    - name: "80"
      protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sas-event-stream-processing-studio-app
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 500m
    TEMPLATE_ESP_MULTInginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
    TEMPLATE_ESP_MULTInginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$escaped_request_uri"
spec:
  rules:
  - host: TEMPLATE_ESP_NAMESPACE.TEMPLATE_ESP_DOMAIN
    http:
      paths:
      - backend:
          serviceName: sas-event-stream-processing-studio-app # the service to hit
          servicePort: 80            # externally exposed port
        path: /SASEventStreamProcessingStudio
  TEMPLATE_ESP_MULTItls:
  TEMPLATE_ESP_MULTI- hosts:
  TEMPLATE_ESP_MULTI  - sckolo.sas.com
  TEMPLATE_ESP_MULTI  secretName: foo
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: sas-event-stream-processing-studio-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sas-event-stream-processing-studio-app
  template:
    metadata:
      labels:
        app: sas-event-stream-processing-studio-app
    spec:
      serviceAccountName: esp-operator
      containers:
      - name: espstudio-container
        image: TEMPLATE_ESPSTUDIO_IMAGE
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: SAS_MULTI_TENANCY_ENABLED
          value: "true"
        - name: SAS_ESP_COMMON_KUBERNETES
          value: "true"
        - name: SAS_ESP_COMMON_KUBERNETES_NAMESPACE
          value: TEMPLATE_ESP_NAMESPACE
        #
        # Below is the postgres config
        #
        - name: ESP_STUDIO_DB
          value: "true"
        - name: spring_datasource_url
          value: "jdbc:postgresql://postgres-service:80/esp"
        - name: spring_datasource_username
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key:  username
        - name: spring_datasource_password
          valueFrom:
            secretKeyRef:
               name: postgres-secret
               key:  password
        - name: spring_datasource_username
          value: "esp"
        - name: spring_datasource_password
          value: "esp_in_cloud"
        - name: spring_datasource_platform
          value: "postgresql"
        - name: spring_datasource_driver_class_name
          value: "org.postgresql.Driver"
