kind: Service
apiVersion: v1
metadata:
  name: sas-event-stream-processing-studio-app
spec:
  selector:
    app: sas-event-stream-processing-studio-app
  ports:
    - name: "80"
      protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sas-event-stream-processing-studio-app
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/ingress.allow-http: "false"
    nginx.ingress.kubernetes.io/proxy-body-size: 500m
    nginx.ingress.kubernetes.io/rewrite-target: /SASEventStreamProcessingStudio/$2
    TEMPLATE_ESP_MULTInginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
    TEMPLATE_ESP_MULTInginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$escaped_request_uri"
spec:
  rules:
  - host: TEMPLATE_ESP_NAMESPACE.TEMPLATE_ESP_DOMAIN
    http:
      paths:
      - backend:
          serviceName: sas-event-stream-processing-studio-app # the service to hit
          servicePort: 80            # externally exposed port
        path: /SASEventStreamProcessingStudio(/|$)(.*)
  tls:
  - hosts:
    - TEMPLATE_ESP_NAMESPACE.TEMPLATE_ESP_DOMAIN
    secretName: foo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sas-event-stream-processing-studio-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sas-event-stream-processing-studio-app
  template:
    metadata:
      annotations:
        seccomp.security.alpha.kubernetes.io/pod: runtime/default
      labels:
        app: sas-event-stream-processing-studio-app
    spec:
      TEMPLATE_ESP_AZUREimagePullSecrets:
      TEMPLATE_ESP_AZURE  - name: acr-secret
      securityContext:
        runAsUser:  1001
        runAsGroup: 1001
        runAsNonRoot: true
      serviceAccountName: sas-esp-clients
      containers:
      - name: espstudio-container
        image: TEMPLATE_ESPSTUDIO_IMAGE
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsGroup: 1001
          runAsUser: 1001
          runAsNonRoot: true        
        ports:
        - containerPort: 8080          
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: true
          capabilities:
            add: []
            drop:
            - ALL
        env:
        - name: SAS_MULTI_TENANCY_ENABLED
          value: "true"
        - name: SAS_ESP_COMMON_KUBERNETES
          value: "true"
        - name: SAS_ESP_COMMON_KUBERNETES_NAMESPACE
          value: TEMPLATE_ESP_NAMESPACE
        - name: SAS_ESP_COMMON_KUBERNETES_DEFAULTS_PERSISTENTVOLUMECLAIM
          value: esp-pv
        - name: SAS_ESP_COMMON_APP_AUTHZ_COOKIE
          value: "true"
        - name: SAS_ESP_COMMON_APP_AUTHZ_COOKIE_NAME
          value: "_oauth2_proxy"
        #
        # Below is the postgres config
        #
        - name: ESP_STUDIO_DB
          value: "true"
        - name: spring_datasource_url
          value: "jdbc:postgresql://postgres-service:80/esp"
        - name: spring_datasource_username
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key:  username
        - name: spring_datasource_password
          valueFrom:
            secretKeyRef:
               name: postgres-secret
               key:  password
        - name: spring_datasource_platform
          value: "postgresql"
        - name: spring_datasource_driver_class_name
          value: "org.postgresql.Driver"
        volumeMounts:
          - name: tmpdir
            mountPath: /tmp
      volumes:
        - name: tmpdir
          emptyDir: {}
