apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: esp-pv
spec:
  storageClassName: "TEMPLATE_ESP_STORAGECLASS_RWX"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
