kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sas-esp-oproxy
subjects:
  - kind: ServiceAccount
    name: sas-esp-oproxy
roleRef:
  kind: Role
  name: sas-esp-oproxy
  apiGroup: rbac.authorization.k8s.io
