apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: sas-esp-clients
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
  - watch

- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get

- apiGroups:
  - iot.sas.com
  resources:
  - espservers
  - espconfigs
  verbs:
  - get
  - list

- apiGroups:
  - iot.sas.com
  resources:
  - espservers
  verbs:
  - create
  - watch
  - delete