kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sas-esp-clients
subjects:
  - kind: ServiceAccount
    name: sas-esp-clients
roleRef:
  kind: Role
  name: sas-esp-clients
  apiGroup: rbac.authorization.k8s.io
