apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: esploadbalancers.iot.sas.com
spec:
  group: iot.sas.com
  names:
    kind: ESPLoadBalancer
    listKind: ESPLoadBalancerList
    plural: esploadbalancers
    singular: esploadbalancer
  scope: Namespaced
  versions:
  - name: v1alpha1
    # Each version can be enabled/disabled by Served flag.
    served: true
    # One and only one version must be marked as the storage version.
    storage: true
    subresources:
      status: {}
