apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: espservers.iot.sas.com
spec:
  group: iot.sas.com
  names:
    kind: ESPServer
    listKind: ESPServerList
    plural: espservers
    singular: espserver
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        access:
          properties:
            externalURL:
              type: string
            internalHostName:
              type: string
            internalHttpPort:
              format: int64
              type: integer
            state:
              description: 'INSERT ADDITIONAL STATUS FIELD - define observed state of cluster Important: Run "operator-sdk generate k8s" to regenerate code after modifying this file Add custom validation using kubebuilder tags: https://book.kubebuilder.io/beyond_basics/generating_crd.html'
              type: string
          type: object
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            espProperties:
              additionalProperties:
                type: string
              nullable: true
              type: object
            failover:
              type: boolean
            loadBalancePolicy:
              type: string
            loadBalancerTemplate:
              nullable: true
              properties:
                spec:
                  nullable: true
                  properties:
                    replicas:
                      description: number of replicas
                      format: int64
                      type: integer
                  type: object
              type: object
            projectTemplate:
              nullable: true
              properties:
                autoscale:
                  properties:
                    maxReplicas:
                      format: int32
                      type: integer
                    metrics:
                      items:
                        type: object
                      type: array
                    minReplicas:
                      format: int32
                      type: integer
                  required:
                  - minReplicas
                  - maxReplicas
                  - metrics
                  type: object
                spec:
                  nullable: true
                  properties:
                    replicas:
                      description: number of replicas
                      format: int64
                      type: integer
                  type: object
              type: object
          required:
          - espProperties
          - loadBalancePolicy
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
