apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: esploadbalancers.iot.sas.com
spec:
  group: iot.sas.com
  names:
    kind: ESPLoadBalancer
    listKind: ESPLoadBalancerList
    plural: esploadbalancers
    singular: esploadbalancer
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
