apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: esp-clients-logout
  annotations:
    kubernetes.io/ingress.allow-http: "false"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: "/oauth2/sign_out?rd=https%3A%2F%2F$host/uaa/logout.do?redirect=https%3A%2F%2F$host/uaa/login"
spec:
  rules:
  - host: TEMPLATE_ESP_NAMESPACE.TEMPLATE_ESP_DOMAIN
    http:
      paths:
      - backend:
          serviceName: oauth2-proxy
          servicePort: 4180
        path: /SASEventStreamProcessingStudio/logout
  - host: TEMPLATE_ESP_NAMESPACE.TEMPLATE_ESP_DOMAIN
    http:
      paths:
      - backend:
          serviceName: oauth2-proxy
          servicePort: 4180
        path: /SASEventStreamManager/logout
  - host: TEMPLATE_ESP_NAMESPACE.TEMPLATE_ESP_DOMAIN
    http:
      paths:
      - backend:
          serviceName: oauth2-proxy
          servicePort: 4180
        path: /SASEventStreamProcessingStreamviewer/logout
  tls:
  - hosts:
    - TEMPLATE_ESP_NAMESPACE.TEMPLATE_ESP_DOMAIN
    secretName: logout-clients-sas-com-tls
