apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sas-esp-operator
rules:
  - apiGroups:
      - apiextensions.k8s.io
    resourceNames:
      - espconfigs.iot.sas.com
      - esploadbalancers.iot.sas.com
      - esprouters.iot.sas.com
      - espservers.iot.sas.com
      - espupdates.iot.sas.com
    resources:
      - customresourcedefinitions
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - storage.k8s.io
    resources:
      - storageclasses
    verbs:
      - get
      - list
      - watch
