kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sas-esp-operator
subjects:
  - kind: ServiceAccount
    name: sas-esp-operator
    namespace: TEMPLATE_ESP_NAMESPACE
roleRef:
  kind: ClusterRole
  name: sas-esp-operator
  apiGroup: rbac.authorization.k8s.io
